CREATE TYPE bookmark_articles AS ENUM (
    1,
    2,
    3,
    4,
    5
)

CREATE TABLE blogful_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    category TEXT
    rating rating TEXT NOT NULL
);